name: Build trove-classifiers with VS 2019

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout trove-classifiers
      uses: actions/checkout@v4
      with:
        repository: pypa/trove-classifiers
        ref: 2026.1.14.14

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
   
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel setuptools==82.0.0 build
      shell: powershell

    - name: Build and install wheel
      run: |
        pip wheel . -w .
        
      shell: powershell
